### ISSUE TITLE
这是一个非常好的idea，但是obsidian1.5.3没法用

### ISSUE THREAD

**Issue by yonghsuan** [lithStudy/obsidian-simple-mindmap#12]
我在obsidian1.5.3中想启用该插件，提示我错误，无法启用。

**Comment by ysjiang4869** [comment]
同样的问题，是否有编译的说明？使用nodejs v20.12.0 编译出错

**Comment by lithStudy** [comment]
> 我在obsidian1.5.3中想启用该插件，提示我错误，无法启用。

我这边没有发现这个问题，我目前已经是V1.5.12也没有问题
